[build]
  publish = "build"
  functions = "/src/lambda"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/sicknick"
  to = "https://www.gofundme.com/f/95xqrr-officer-brian-d-sicknick-memorial"
  status = 302

[[redirects]]
  from = "/quarter"
  to = "https://docs.google.com/drawings/d/1i9vdWauHwfNQdq6gZLVxEd02Fms94IkixeOzV5QDXds/template/preview"
  status = 302

[[redirects]]
  from = "/half"
  to = "https://docs.google.com/drawings/d/1D3wiuL5N2ZOjRWTpvnmQklB8SaCiOie1s_z1dKFDtIA/template/preview"
  status = 302

[[redirects]]
  from = "/full"
  to = "https://docs.google.com/drawings/d/1ZhRgBxDK5k_vfzj-QSQbmYjIBa7b4voJh9GU-bGMWNA/template/preview"
  status = 302

[[redirects]]
  from = "/buy-spread"
  to = "https://www.saintanselms.org/parents2/parent-spread"
  status = 302

[[redirects]]
  from = "/spread-help"
  to = "https://support.google.com/docs/answer/179740"
  status = 302

[[redirects]]
  from = "/send-spread"
  to = "https://docs.google.com/forms/d/e/1FAIpQLScT-pL94mSZYSwINd0O3GpOerCwCqxk7NWboMuXbZ10veDDtA/viewform"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200