[build]
  publish = "build"
  functions = "/src/lambda"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/AwardsStream"
  to = "https://www.youtube.com/watch?v=7UBZp9w0f0s"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200